### PR TITLE
Update Promises for Generics

### PR DESCRIPTION
**Pull request by cnuss**
Hey @katsanva!

I'd like your input before I push this forward to DefinitelyTyped (and continue down this rabbit hole further)...

Long story short, having the types on this library return `any` has been confusing, so I wanted to take a stab at adding optional typing, but that ended up leading to some significant restructuring of your initial Type Definitions.

Here's my approach so far:
 - Query, Scan, and Model are now generically typed.
 - I only took a stab at adding Types to the Promised responses, but the Callback functions could be typed as well if you're happy with my approach (so far).
 - The existing test shows no linting errors in VSCode and when running `npm run test` 🙌 

Open questions for you:
  - How do you feel about this approach, any and all feedback is greatly appreciated
  - Obviously the tests need to be updated, what approach should I take?
     - Include tests on Promises
     - Probably update the tests so they can run locally (wrap in async/promises/etc)?
 
I also have to admit that I'm relatively new to TypeScript so any and all input would be great.

### CODE REVIEW

**Comment by katsanva** [comment]
Hi. @cnuss. Thanks for such a great rework!

Actually, I haven't been using the dynamodb module for some time so I hope these updates are fine and match the actual package.

Please update the version in `index.d.ts`.

I assume that you can update the tests just adding the promise usage right after the callback ones e.g.
```ts
dynamo.createTables(err => {
    if (err) {
        console.log('Error creating tables: ', err);
    } else {
        console.log('Tables has been created');
    }
});

dynamo.createTables()
  .then(() => console.log('Tables has been created'))
  .catch(err => console.log('Error creating tables: ', err));
```

That will allow having clear visibility on changes.

Also, I think that you will have some additional hints when making the PR to the DT repo.

**Comment by cnuss** [comment]
thanks for the feedback @katsanva 

one thing i forgot to ask, how do you feel about my changes from the Namespace to Classes/Interface in Model.d.ts? I basically was screwing around with things while the linter complained, until I had no more linter complaints.

**Comment by katsanva** [comment]
I think that you are fine to go. The DT repo tests will be run on the PR creation so you will figure out in case some issues.

**Comment by cnuss** [comment]
Cool thanks for the input!

Also, how did you go about inferring the response types from the functions, this dynamodb library has a way of adding/removing props from functions based on some conditional logic, is there an art of some kind you did to figure it out?

**Comment by cnuss** [comment]
@katsanva closing this in favor of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53536 

Looking forward to your feedback there!

**Pull request closed without merging**
